# Generated by Django 5.1.7 on 2025-05-28 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('patient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patients.patient')),
                ('emergency_level', models.CharField(max_length=50)),
                ('arrival_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            bases=('patients.patient',),
        ),
    ]
